
export const agentExamplesEs: Record<string, string[]> = {
    "asesor-fiscal": [
        "¿Cómo tributan mis dividendos de una LLC en USA viviendo en España?",
        "¿Qué gastos puedo deducir realmente como nómada digital?",
        "Explícame el modelo 720 y las sanciones por no presentarlo a tiempo.",
        "¿Cómo funciona la Ley Beckham y cuáles son los requisitos de 2024?",
        "¿IVA intracomunitario: cómo me doy de alta en el ROI?",
        "¿Pagaré impuestos en España si vendo mi casa en el extranjero?",
        "¿Cuál es la retención mínima de IRPF que me corresponde este año?",
        "Diferencias fiscales entre una SL y ser Autónomo (Estimación Directa).",
        "¿Cómo declarar mis beneficios de Amazon FBA sin errores?",
        "¿Qué es la Doble Imposición y cómo me acojo al convenio USA-España?",
        "¿Impuesto de Patrimonio: cuándo empiezo a estar obligado a declarar?",
        "¿Tributan las donaciones de padres a hijos en mi comunidad autónoma?",
        "Afectación de la nueva Ley de Vivienda en mis rendimientos de alquiler.",
        "¿Cómo tributa la venta de una startup (Exit) para los fundadores?",
        "¿Puedo deducir el renting de un vehículo eléctrico al 100%?",
        "¿Qué es una Inspección de Gestión y qué documentos debo tener listos?",
        "¿Cómo declarar ingresos por publicidad en redes sociales (OnlyFans/YouTube)?",
        "Tributación de las Stock Options (Phantom Shares) para empleados.",
        "¿Cuándo prescribe una deuda tributaria con Hacienda?",
        "Impacto fiscal del cambio de residencia a Andorra o Portugal."
    ],
    "asesor-extranjeria": [
        "¿Requisitos actuales para la Golden Visa (Visa por Inversión)?",
        "¿Cómo solicitar el Arraigo Social después de 3 años en el país?",
        "¿Diferencias entre permiso de residencia y permiso de trabajo?",
        "¿Puedo reagrupar a mis padres si tengo residencia de larga duración?",
        "¿Cuánto tiempo tarda la nacionalidad por residencia tras presentarla?",
        "¿Visa de Nómada Digital: requisitos económicos y de seguridad social?",
        "¿Qué es la tarjeta comunitaria y quién tiene derecho a solicitarla?",
        "¿Cómo renovar mi NIE de estudiante si he terminado el grado?",
        "¿Qué pasa si pierdo mi trabajo con un permiso inicial de residencia?",
        "Requisitos para la Ley de Memoria Democrática (Nacionalidad Nietos).",
        "¿Cómo obtener el NIE por primera vez si soy ciudadano de la UE?",
        "¿Asilo político: qué documentos necesito para la entrevista?",
        "¿Cómo homologar mi título de medicina extranjero paso a paso?",
        "¿Puedo viajar fuera del país mientras mi renovación está en trámite?",
        "¿Qué es el informe de integración y dónde se solicita?",
        "¿Cómo cambiar de visado de estudiante a permiso de trabajo (Modificación)?",
        "¿Requisitos para la residencia por razones humanitarias?",
        "¿Nacionalidad por matrimonio: cuánto tiempo debo estar residiendo?",
        "¿Qué es la carta de invitación y qué riesgos legales tiene?",
        "¿Cómo cancelar mis antecedentes penales para solicitar la nacionalidad?"
    ],
    "asesor-mercantil": [
        "¿Qué debe incluir obligatoriamente un Pacto de Socios robusto?",
        "¿Diferencia entre Administrador Solidario y Administrador Mancomunado?",
        "¿Cómo realizar una ampliación de capital por compensación de créditos?",
        "Cláusulas de Drag Along y Tag Along: ¿Cuál me protege más?",
        "¿Responsabilidad de administradores: cuándo respondo con mi patrimonio?",
        "Procedimiento legal para disolver y liquidar una SL sin deudas.",
        "¿Cómo redactar un contrato de Vesting para mis desarrolladores?",
        "¿Qué es el Compliance Corporativo y por qué lo necesita mi empresa?",
        "Conflictos entre socios: ¿Cómo echar a un socio sin bloquear la empresa?",
        "¿Cómo transformar mi SL en una SA de forma legal?",
        "¿Qué es una auditoría de cuentas y cuándo es obligatoria?",
        "¿Cómo registrar mi empresa en el Registro Mercantil Central?",
        "Contratos de confidencialidad (NDA): ¿Qué penalización debo poner?",
        "¿Cómo gestionar el reparto de dividendos legalmente?",
        "¿Sociedad Profesional vs Sociedad Limitada: qué elegir?",
        "¿Qué es el levantamiento del velo corporativo?",
        "¿Cómo comprar una empresa (M&A) y qué es la Due Diligence?",
        "Inscripción del Beneficiario Real (Hoja 2 del Registro Mercantil).",
        "¿Cómo celebrar una Junta General de forma telemática válida?",
        "Derechos de suscripción preferente ante nuevos inversores."
    ],
    "asesor-laboral": [
        "¿Cómo calculo mi finiquito e indemnización tras un despido?",
        "¿Es legal que me despidan estando de baja médica?",
        "¿Qué es un Falso Autónomo y cómo denunciar mi situación?",
        "Diferencias entre Despido Objetivo y Despido Improcedente.",
        "¿Cómo solicitar una reducción de jornada por cuidado de hijo?",
        "¿Cuántas vacaciones me corresponden si trabajo a tiempo parcial?",
        "¿Qué es el ERTE de limitación y cuánto cobraré del SEPE?",
        "Acoso laboral (Mobbing): ¿Qué pruebas necesito para la denuncia?",
        "¿Me pueden obligar a hacer horas extras sin previo aviso?",
        "Contrato de formación: ¿Cuál es el salario mínimo legal?",
        "¿Cómo impugnar un alta médica si sigo enfermo?",
        "Derecho a la desconexión digital fuera del horario laboral.",
        "¿Qué es el período de prueba y puedo cobrar paro si me despiden?",
        "¿Cambio de convenio colectivo: ¿Pueden bajarme el sueldo?",
        "¿Puedo teletrabajar desde otro país legalmente?",
        "Excedencias laborales: ¿Tengo derecho de reserva de puesto?",
        "¿Qué es la IT (Incapacidad Temporal) y cuánto paga la Mutua?",
        "¿Cómo denunciar a mi empresa ante la Inspección de Trabajo?",
        "Brecha salarial: ¿Cómo pedir el registro retributivo de mi empresa?",
        "¿Pérdida de confianza en directivos: ¿Conlleva indemnización?"
    ],
    "asesor-penal": [
        "¿Qué hacer si recibo una citación como 'Investigado' en el juzgado?",
        "¿Diferencia entre estafa y apropiación indebida (ejemplos)?",
        "¿Cuándo prescribe un delito por blanqueo de capitales?",
        "¿Cómo cancelar mis antecedentes penales y policiales?",
        "Delitos informáticos: hacking, phishing y su castigo legal.",
        "¿Qué es la responsabilidad penal de las personas jurídicas?",
        "¿Injurias y calumnias en redes sociales: qué riesgo penal tiene?",
        "¿Cómo solicitar la libertad bajo fianza y de qué depende?",
        "Delito de abandono de familia: impago de pensión de alimentos.",
        "¿Qué hacer ante un control de alcoholemia positivo?",
        "¿Cómo poner una querella criminal en lugar de una denuncia?",
        "Defensa ante el delito de revelación de secretos de empresa.",
        "¿Requisitos para la suspensión de la pena de prisión?",
        "¿Qué es el Habeas Corpus y cuándo se puede solicitar?",
        "Delitos contra la salud pública y sus grados de pena.",
        "¿Qué es un juicio rápido y cuándo se aplica?",
        "Derechos del detenido en comisaría: abogado y traducción.",
        "Apropiación de fondos de la empresa (Administración Desleal).",
        "¿Delitos de odio: qué límites tiene la libertad de expresión?",
        "Negligencia profesional: ¿Puede ser un delito penal?"
    ],
    "asesor-aeronautico": [
        "¿Cómo reclamar un vuelo cancelado y cuánto dinero recibiré?",
        "¿Requisitos para volar drones de forma comercial en ciudad?",
        "¿Qué documentos legales necesito para comprar un Jet Privado?",
        "¿Diferencia entre Overbooking y Denegación de embarque?",
        "¿Cómo reclamar daños en mi equipaje facturado (Convenio Montreal)?",
        "¿Es legal usar drones para vigilancia de fincas privadas?",
        "Normativa EASA para el transporte de baterías de litio.",
        "¿Cómo obtener la licencia de piloto de drones (A1/A3)?",
        "¿Responsabilidad del comandante de vuelo en emergencias?",
        "Derecho de reembolso vs bono compensatorio (Tus opciones).",
        "Indemnización por retraso superior a 3 horas: cómo pedirla.",
        "¿Cómo registrar un dron de más de 250 gramos en AESA?",
        "Reglas para el transporte aéreo de animales de compañía.",
        "¿Qué seguros obligatorios necesita una aeronave privada?",
        "Contratos de Dry Lease vs Wet Lease de aviones.",
        "Derechos de pasajeros con movilidad reducida (PMR).",
        "¿Cómo impugnar una multa aérea administrativa?",
        "Jurisdicción legal en delitos ocurridos a bordo de un vuelo.",
        "Permisos para vuelos fotogramétricos o comerciales.",
        "Regulación de aeródromos privados y helipuertos."
    ],
    "asesor-civil": [
        "¿Cómo redactar un testamento para evitar conflictos entre hijos?",
        "¿Diferencias entre separación y divorcio (Contencioso vs Acuerdo)?",
        "¿Qué es la legítima y se puede desheredar a un hijo?",
        "Liquidación de gananciales: ¿Cómo se reparten los bienes?",
        "¿Cómo solicitar la custodia compartida internacional?",
        "¿Qué es el convenio regulador y qué pasa si se incumple?",
        "¿Incapacidad legal y curatela: cómo proteger a un mayor?",
        "¿Cómo reclamar una herencia sin testamento (Abintestato)?",
        "¿Qué es la pensión compensatoria y cuánto tiempo dura?",
        "Compra de vivienda: ¿Qué es el contrato de Arras y sus riesgos?",
        "¿Cómo impugnar la paternidad de un hijo?",
        "Donaciones en vida vs Herencia: ¿Qué sale más barato?",
        "¿Qué es una pareja de hecho y qué derechos tiene en España?",
        "Reclamación de deudas entre particulares: el juicio monitorio.",
        "¿Cómo gestionar el patrimonio de un menor de edad?",
        "¿Servidumbre de paso: qué derechos tengo sobre el vecino?",
        "¿Qué es el usufructo vitalicio y cómo se valora?",
        "División de cosa común: ¿Cómo vender una casa con mi ex?",
        "¿Cómo cambiar mis apellidos legalmente?",
        "Poderes notariales: ¿Cómo revocar un poder dado a un tercero?"
    ],
    "asesor-pi": [
        "¿Cómo registrar mi marca en la OEPM y cuánto cuesta?",
        "¿Diferencia entre Marca Nacional, Europea e Internacional?",
        "¿Cómo proteger el código fuente de mi software (Copyright)?",
        "¿Qué hacer si alguien usa mi nombre de dominio web?",
        "¿Cómo registrar una patente internacional (Tratado PCT)?",
        "Propiedad Industrial vs Intelectual: diferencias clave.",
        "¿Cómo redactar un contrato de licencia de uso de mi marca?",
        "¿Qué es el Secreto Comercial y cómo protegerlo legalmente?",
        "¿Puedo registrar un sonido, un olor o un color como marca?",
        "Reclamación legal por uso no autorizado de mis fotos en RRSS.",
        "¿Cómo impugnar el registro de una marca similar a la mía?",
        "¿Qué es el 'Fair Use' y cuándo puedo usar contenido ajeno?",
        "Traspaso de derechos de autor de un creador a una empresa.",
        "¿Cómo registrar un diseño industrial antes de lanzarlo?",
        "Protección legal de bases de datos y algoritmos.",
        "Infracción de marca en Amazon: ¿Cómo reportar falsificaciones?",
        "¿Qué es la nulidad de marca por falta de uso?",
        "Contratos de patrocinio e influencers: cesión de imagen.",
        "¿Cómo proteger una receta o una fórmula química?",
        "Cesión de derechos en contratos de freelance creativos."
    ],
    "asesor-inmobiliario": [
        "¿Qué documentos revisar antes de firmar una compraventa?",
        "¿Cómo detectar cargas o embargos en la Nota Simple?",
        "¿Qué es la Plusvalía Municipal y quién debe pagarla?",
        "Contrato de alquiler 2024: ¿Cuánto puedo subir la renta?",
        "¿Cómo desahuciar a un inquilino por impago legalmente?",
        "¿Qué es la ITE de un edificio y quién paga la derrama?",
        "Seguro de impago de alquiler: ¿Qué cubre realmente?",
        "Diferencias entre Arras Confirmatorias, Penales y Penitenciales.",
        "¿Cómo solicitar una hipoteca paso a paso (Gastos y AJD)?",
        "¿Qué es el derecho de tanteo y retracto de la Administración?",
        "¿Cómo denunciar ruidos o molestias en mi comunidad?",
        "Alquiler vacacional (Airbnb): ¿Qué licencias necesito?",
        "Usufructo vs Nuda Propiedad: ¿Cómo vender una casa conmigo dentro?",
        "¿Cómo reclamar defectos de construcción en obra nueva?",
        "Impuesto de transmisiones (ITP) vs IVA en viviendas.",
        "Certificado energético: ¿Es obligatorio para alquilar?",
        "¿Qué es la cédula de habitabilidad y cómo renovarla?",
        "¿Cómo cambiar el uso de local a vivienda legalmente?",
        "Gestión de okupas: medidas legales urgentes a tomar.",
        "¿Cómo impugnar el acta de una reunión de vecinos?"
    ],
    "asesor-cripto": [
        "¿Cómo tributan mis ganancias de trading en criptomonedas?",
        "Modelo 721: ¿Debo declarar mis criptos en exchanges extranjeros?",
        "¿Qué hacer si he sido víctima de una estafa cripto (Scam)?",
        "Tributación NFT: ¿Es venta de bien o prestación de servicios?",
        "¿Cómo justificar el origen de los fondos ante mi banco (Compliance)?",
        "Staking, Farming y Airdrops: ¿Cómo declararlos a Hacienda?",
        "¿Sanciones por no declarar criptos: cuánto me pueden multar?",
        "Regulación MiCA en Europa: ¿Qué cambia para el usuario?",
        "¿Cómo heredar legalmente bitcoins y activos digitales?",
        "Contratos inteligentes (Smart Contracts): ¿Tienen validez legal?",
        "¿Cómo declarar mis recompensas de minería (Proof of Work)?",
        "Protocolos AML/KYC en cuentas institucionales cripto.",
        "Pérdida de llaves privadas: ¿Puedo deducir la pérdida patrimonial?",
        "¿Es legal pagar sueldos en stablecoins en mi país?",
        "DAOs: ¿Cómo tributa un miembro de una organización autónoma?",
        "¿Invertir en cripto con una SL o a título personal?",
        "Declaración de 'Hard Forks' de activos digitales.",
        "¿Cómo declarar préstamos DeFi y liquidaciones?",
        "Protección al inversor ante la quiebra de un Exchange.",
        "Fiscalidad de los juegos Play-to-Earn (P2E)."
    ]
};

export const agentExamplesEn: Record<string, string[]> = {
    "asesor-fiscal": [
        "How are my LLC dividends from the USA taxed while living in Spain?",
        "What expenses can I really deduct as a digital nomad?",
        "Explain Form 720 to me and the penalties for not filing on time.",
        "How does the Beckham Law work and what are the 2024 requirements?",
        "Intra-community VAT: how do I register for the ROI?",
        "Will I pay taxes in Spain if I sell my house abroad?",
        "What is the minimum personal income tax retention corresponding to me this year?",
        "Fiscal differences between an SL (LLC) and being a Freelancer (Direct Estimation).",
        "How to declare my Amazon FBA profits without errors?",
        "What is Double Taxation and how do I benefit from the USA-Spain treaty?",
        "Wealth Tax: when do I start being obliged to declare?",
        "Are donations from parents to children taxed in my autonomous community?",
        "Impact of the new Housing Law on my rental income.",
        "How is the sale of a startup (Exit) taxed for founders?",
        "Can I deduct the 100% renting of an electric vehicle?",
        "What is a Management Inspection and what documents should I have ready?",
        "How to declare income from advertising on social networks (OnlyFans/YouTube)?",
        "Taxation of Stock Options (Phantom Shares) for employees.",
        "When does a tax debt with the Treasury prescribe?",
        "Fiscal impact of changing residency to Andorra or Portugal."
    ],
    "asesor-extranjeria": [
        "Current requirements for the Golden Visa (Visa by Investment)?",
        "How to apply for Social Integration (Arraigo Social) after 3 years in the country?",
        "Differences between residence permit and work permit?",
        "Can I reunite with my parents if I have a long-term residence?",
        "How long does nationality by residence take after submission?",
        "Digital Nomad Visa: economic and social security requirements?",
        "What is the community card and who has the right to apply?",
        "How to renew my student NIE if I have finished my degree?",
        "What happens if I lose my job with an initial residence permit?",
        "Requirements for the Democratic Memory Law (Grandchildren's Nationality).",
        "How to obtain the NIE for the first time if I am a EU citizen?",
        "Political Asylum: what documents do I need for the interview?",
        "How to legalize my foreign medical degree step by step?",
        "Can I travel outside the country while my renewal is pending?",
        "What is the integration report and where is it requested?",
        "How to change from a student visa to a work permit (Modification)?",
        "Requirements for residence on humanitarian grounds?",
        "Nationality by marriage: how long must I be residing?",
        "What is the invitation letter and what legal risks does it have?",
        "How to cancel my criminal records to apply for nationality?"
    ],
    "asesor-mercantil": [
        "What must a robust Shareholders' Agreement necessarily include?",
        "Difference between Joint and Several Administrator and Joint Administrator?",
        "How to perform a capital increase by credit compensation?",
        "Drag Along and Tag Along clauses: which one protects me more?",
        "Directors' liability: when do I respond with my personal assets?",
        "Legal procedure to dissolve and liquidate an SL without debts.",
        "How to draft a Vesting contract for my developers?",
        "What is Corporate Compliance and why does my company need it?",
        "Conflicts between partners: how to remove a partner without blocking the company?",
        "How to transform my SL into an SA legally?",
        "What is an accounts audit and when is it mandatory?",
        "How to register my company in the Central Commercial Registry?",
        "Non-Disclosure Agreements (NDA): what penalty should I set?",
        "How to manage dividend distribution legally?",
        "Professional Society vs. Limited Society: what to choose?",
        "What is the lifting of the corporate veil?",
        "How to buy a company (M&A) and what is Due Diligence?",
        "Beneficial Owner registration (Sheet 2 of the Commercial Registry).",
        "How to validly hold a General Meeting remotely?",
        "Pre-emptive subscription rights before new investors."
    ],
    "asesor-laboral": [
        "How do I calculate my settlement and compensation after a dismissal?",
        "Is it legal to be fired while on medical leave?",
        "What is a False Freelancer and how to report my situation?",
        "Differences between Objective Dismissal and Unfair Dismissal.",
        "How to request a reduction in working hours for childcare?",
        "How much vacation corresponds to me if I work part-time?",
        "What is the ERTE of limitation and how much will I receive from the SEPE?",
        "Workplace harassment (Mobbing): what evidence do I need to report?",
        "Can they force me to work overtime without prior notice?",
        "Training contract: what is the minimum legal salary?",
        "How to challenge a medical discharge if I am still ill?",
        "Right to digital disconnection outside of working hours.",
        "What is the probationary period and can I collect unemployment if I'm fired?",
        "Change of collective agreement: can they lower my salary?",
        "Can I work remotely from another country legally?",
        "Labor leaves of absence: do I have the right to job reservation?",
        "What is the IT (Temporary Incapacity) and how much does the Mutual pay?",
        "How to report my company to the Labor Inspection?",
        "Wage gap: how to request the remuneration register of my company?",
        "Loss of confidence in executives: does it involve compensation?"
    ],
    "asesor-penal": [
        "What to do if I receive a citation as 'Under Investigation' in court?",
        "Difference between fraud and misappropriation (examples)?",
        "When does a crime for money laundering prescribe?",
        "How to cancel my criminal and police records?",
        "Computer crimes: hacking, phishing and their legal punishment.",
        "What is the criminal liability of legal entities?",
        "Libel and slander on social networks: what criminal risk does it have?",
        "How to request bail and what does it depend on?",
        "Crime of family abandonment: non-payment of child support.",
        "What to do after a positive breathalyzer test?",
        "How to file a criminal complaint instead of a report?",
        "Defense against the crime of revealing company secrets.",
        "Requirements for the suspension of the prison sentence?",
        "What is Habeas Corpus and when can it be requested?",
        "Crimes against public health and their degrees of penalty.",
        "What is a fast-track trial and when does it apply?",
        "Rights of the detainee at the police station: lawyer and translation.",
        "Misappropriation of company funds (Unfaithful Administration).",
        "Hate crimes: what limits does freedom of expression have?",
        "Professional negligence: can it be a criminal offense?"
    ],
    "asesor-aeronautico": [
        "How to claim a cancelled flight and how much money will I receive?",
        "Requirements for flying drones commercially in the city?",
        "What legal documents do I need to buy a Private Jet?",
        "Difference between Overbooking and Boarding Denial?",
        "How to claim damages to my checked baggage (Montreal Convention)?",
        "Is it legal to use drones for surveillance of private estates?",
        "EASA regulations for the transport of lithium batteries.",
        "How to obtain the drone pilot license (A1/A3)?",
        "Responsibility of the flight commander in emergencies?",
        "Right to refund vs compensatory voucher (Your options).",
        "Compensation for delay exceeding 3 hours: how to request it.",
        "How to register a drone over 250 grams in AESA?",
        "Rules for the air transport of pets.",
        "What mandatory insurance does a private aircraft need?",
        "Dry Lease vs Wet Lease aircraft contracts.",
        "Rights of passengers with reduced mobility (PRM).",
        "How to challenge an administrative air fine?",
        "Legal jurisdiction in crimes occurring on board a flight.",
        "Permissions for photogrammetric or commercial flights.",
        "Regulation of private airfields and heliports."
    ],
    "asesor-civil": [
        "How to draft a will to avoid conflicts between children?",
        "Differences between separation and divorce (Contested vs. Agreement)?",
        "What is the statutory share and can a child be disinherited?",
        "Community property liquidation: how are assets divided?",
        "How to request international joint custody?",
        "What is the regulatory agreement and what happens if it's breached?",
        "Legal incapacity and guardianship: how to protect an elderly person?",
        "How to claim an inheritance without a will (Intestate)?",
        "What is alimony and how long does it last?",
        "Buying a home: what is the Deposit Contract (Arras) and its risks?",
        "How to challenge the paternity of a child?",
        "Donations in life vs. Inheritance: which is cheaper?",
        "What is a domestic partnership and what rights does it have in Spain?",
        "Debt claims between individuals: the payment order procedure.",
        "How to manage the assets of a minor?",
        "Right of way (easement): what rights do I have over the neighbor?",
        "What is life usufruct and how is it valued?",
        "Division of common property: how to sell a house with my ex?",
        "How to change my surnames legally?",
        "Notary powers: how to revoke a power given to a third party?"
    ],
    "asesor-pi": [
        "How to register my brand at the OEPM and how much does it cost?",
        "Difference between National, European, and International Brand?",
        "How to protect the source code of my software (Copyright)?",
        "What to do if someone uses my web domain name?",
        "How to register an international patent (PCT Treaty)?",
        "Industrial vs Intellectual Property: key differences.",
        "How to draft a license agreement for my brand?",
        "What is Trade Secret and how to protect it legally?",
        "Can I register a sound, a smell, or a color as a brand?",
        "Legal claim for unauthorized use of my photos on Social Networks.",
        "How to challenge the registration of a brand similar to mine?",
        "What is 'Fair Use' and when can I use third-party content?",
        "Transfer of copyrights from a creator to a company.",
        "How to register an industrial design before launching it?",
        "Legal protection of databases and algorithms.",
        "Brand infringement on Amazon: how to report counterfeits?",
        "What is brand invalidity for lack of use?",
        "Sponsorship and influencer contracts: image transfer.",
        "How to protect a recipe or a chemical formula?",
        "Assignment of rights in creative freelance contracts."
    ],
    "asesor-inmobiliario": [
        "What documents to review before signing a sale?",
        "How to detect charges or liens in the Land Registry (Nota Simple)?",
        "What is the Municipal Capital Gains Tax and who should pay it?",
        "2024 rental contract: how much can I raise the rent?",
        "How to evict a tenant for non-payment legally?",
        "What is the ITE of a building and who pays the assessment?",
        "Rental default insurance: what does it really cover?",
        "Differences between Confirmatory, Penal, and Penitential Deposits.",
        "How to apply for a mortgage step by step (Expenses and AJD)?",
        "What is the right of first refusal and retraction of the Administration?",
        "How to report noise or disturbances in my community?",
        "Vacation rental (Airbnb): what licenses do I need?",
        "Usufruct vs Bare Ownership: how to sell a house with me inside?",
        "How to claim construction defects in new build?",
        "Transfer tax (ITP) vs VAT on homes.",
        "Energy certificate: is it mandatory for renting?",
        "What is the habitability certificate and how to renew it?",
        "How to legally change the use from premises to housing?",
        "Squatter management: urgent legal measures to take.",
        "How to challenge the minutes of a neighborhood meeting?"
    ],
    "asesor-cripto": [
        "How are my cryptocurrency trading gains taxed?",
        "Form 721: should I declare my cryptos on foreign exchanges?",
        "What to do if I've been a victim of a crypto scam?",
        "NFT Taxation: is it asset sale or provision of services?",
        "How to justify the origin of funds to my bank (Compliance)?",
        "Staking, Farming, and Airdrops: how to declare them to the Treasury?",
        "Sanctions for not declaring cryptos: how much can I be fined?",
        "MiCA Regulation in Europe: what changes for the user?",
        "How to legally inherit bitcoins and digital assets?",
        "Smart Contracts: do they have legal validity?",
        "How to declare my mining rewards (Proof of Work)?",
        "AML/KYC protocols on institutional crypto accounts.",
        "Loss of private keys: can I deduct the capital loss?",
        "Is it legal to pay salaries in stablecoins in my country?",
        "DAOs: how is a member of an autonomous organization taxed?",
        "Investing in crypto with an SL or personally?",
        "Declaration of 'Hard Forks' of digital assets.",
        "How to declare DeFi loans and liquidations?",
        "Investor protection before the bankruptcy of an Exchange.",
        "Taxation of Play-to-Earn (P2E) games."
    ]
};

export const agentExamples: Record<string, Record<string, string[]>> = {
    es: agentExamplesEs,
    en: agentExamplesEn
};
